### ISSUE TITLE
Object doesn't support property or method 'assign' 

### ISSUE THREAD

**Issue by mancioshell** [jeffbski/joi-browser#4]
Hi @jeffbski ! Thank you for your helpful project.

It works fine for Google Chrome, but for IE11 there is an issue:

`Object doesn't support property or method 'assign' `

This is caused because Object.assign, used in Joi is not supported in IE11, as E6 Compatibility table shows:

https://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign

Maybe this issue could be solved by object-assign transform babel plugin.
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-object-assign

**Comment by jeffbski** [comment]
Nice catch. Some ES6 features require a polyfill and I didn't realize they were using Object.assign which is one of those features.

As you suggested, I used the babel plugin to transform the code so the polyfill wouldn't be necessary  and it appears to work fine.

Please test it in IE11 since I don't have a copy of that to test in.

I published the new version to npm as 8.0.6.
